---
title: "QOF variation dashboard"
author: "Ian Bates"
output: 
    flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
#    vertical_layout: fill # scroll
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include = FALSE, cache = FALSE}
require("flexdashboard")
require("shiny")
#require("d3heatmap")
require("DT")
require("dplyr")
require("data.table")
require("qofvariation.ncc")

knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(echo = FALSE)

```

Global page {.hidden}
====

```{r global, include = FALSE, cache = FALSE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

#dat <- main(qof_period = "1617", bProcessRaw = FALSE, bLoadData = FALSE)
qv <- qof__main__load(qof_root = "qof-1516")
#qv <- qof__main__load(qof_root = "qof-1617")
#qv <- qof__main__load(qof_root = "qof-1718")

# add an orgtag field
l_add_orgtag <- function(x, c1 = "ccg_code", c2 = "practice_code") {
    x %>%
        mutate(
            orgtag = paste(
                UQ(rlang::sym(c1))
                , UQ(rlang::sym(c2))
            )
        ) %>% invisible()
}

# Add ccg group lookup

lu.orgs.ccgs.groups <- qof__main__load_ccglu()$lu_ccg_groups

# Add display order
#
# Based on ccg_group_type.  
# Manually add CCGs go to 10, practices go to 20.
l_add_display_order <- function(x, c1 = "org.type") {
    x %>% 
        merge(
            lu.orgs.ccgs.groups %>% 
                select(ccg_group_code, display_order = type_display_order) %>%
                unique()
            , by.x = "practice_code", by.y = "ccg_group_code"
            , all.x = TRUE
        ) %>%
        mutate(display_order = ifelse(
            UQ(rlang::sym(c1)) == "england", 0, display_order)
        ) %>%
        mutate(display_order = ifelse(
            UQ(rlang::sym(c1)) == "ccg::instance", 10, display_order)
        ) %>%
        mutate(display_order = ifelse(
            is.na(display_order), 20, display_order)
        )
}

#' Filter indicators by given domain codes
#'
#' @param domain_codes one of c("CL", "PH", "PHAS")
#'
l__filter_domain_codes_tokeep <- function(
    x
    , domain_codes = c("CL", "PH", "PHAS")
) {
    domain_codes <- match.arg(domain.codes)
    
    if ("domain_code" %in% colnames(x)) {
        x %>% filter(domain_code %in% domain_codes) %>% invisible()
    } else {
        x
    }
}

setnames.display <- function(x) {setnames(x, gsub("_|\\.", " ", names(x)))}

# actually load data
orgref <- qv$qof$meta_org #%>% l_add_orgtag()
indmap <- qv$qof$meta_ind #%>% l_add_orgtag()
measures <- qv$measures %>%
    l_add_display_order() %>%
    l__filter_domain_codes_tokeep("CL") #%>% l_add_orgtag()
compare <- qv$compare %>% 
    l_add_display_order("org.type.var") %>%
    l__filter_domain_codes_tokeep("CL") #%>% l_add_orgtag()

practice_grouping <- list(
    orgref %>% 
        # filter out existing ccg groups
        filter(nchar(practice_code) > 3) %>%
        select(practice_code, ccg_code) %>%
        merge(lu.orgs.ccgs.groups, by = "ccg_code", all.y = TRUE) %>%
        select(-type_display_order)
    
    , orgref %>% 
        # filter out existing ccg groups
        filter(nchar(practice_code) > 3) %>%
        # only local ccgs
        filter(ccg_code %in% c(lu.orgs.ccgs.groups$ccg_code %>% unique())) %>%
        select(practice_code, ccg_code) %>%
        mutate(
            ccg_group_type = "ccg"
            , ccg_group_type_name = "ccg"
            , ccg_group_code = ccg_code
            , ccg_group_name = ccg_code
        )
) %>%
    # lapply(function(x){sort(names(x))}) 
    rbindlist(use.names = TRUE)

# For inputs

these_orgtypes <- measures$org.type %>% unique() %>% sort()
these_ccg_groups <- practice_grouping$ccg_group_name %>% unique() %>% sort()
these_ccgs <- measures$ccg_code %>% unique() %>% sort()
these_practices <- practice_grouping$practice_code %>% unique() %>% sort()

these_ind_groups <- measures$indicator_group_code %>% unique() %>% sort()
these_indicators <- measures$indicator_code %>% unique() %>% sort()

these_measures <- measures$m.name %>% unique() %>% sort()

these_comparisons <- compare$compare.type %>% unique() %>% sort()
these_comparisons_param <- compare$compare.param  %>% unique() %>% sort()

these_comparators <- compare$org.type.ref %>% unique() %>% sort()


# for e.g. Heatmap

lu_statsig_num <- fread(input = "
statsig,istatsig
Better,1
Higher,1
Similar,0
Lower,-1
Worse,-1
Not tested,NA
"
)

#
# for stacked bar
#

prevalence <- measures %>%
    filter(
        m.type == "prevalence"
        , m.name == "qofprevalence"
    ) %>%
    select(-m.type) %>%
    dcast(... ~ m.stat) %>%
    rename(register = "numerator") %>%
    select(
        ccg_code, practice_code, indicator_group_code
        , register
    )

lu__register_indicators <- measures %>%
    filter(m.type == "prevalence") %>%
    .$indicator_code %>%
    unique()

these_indicators_noregister <- setdiff(these_indicators, lu__register_indicators)

register <- measures %>%
    filter(
        m.type == "prevalence"
        , m.name == "qofprevalence"
        , m.stat == "numerator"
    ) %>%
    select(-m.type, -m.name) %>%
    dcast(... ~ m.stat) %>%
    rename(register = "numerator") %>%
    select(
        ccg_code, practice_code, indicator_group_code
        , register
    )

counts <- measures %>%
    filter(
        m.type == "performance"
        , m.stat %in% c("numerator", "denominator")
        #, !(indicator_code %in% lu__register_indicators)
    ) %>%
    select(-m.type, -org.type) %>%
    dcast(... ~ m.name + m.stat) %>%
    merge(
        register
        , by = c("ccg_code", "practice_code", "indicator_group_code")
        , all.x = TRUE
    ) %>%
    rename(
        denominator = "achievement_denominator"
        , optimal = "treatment_numerator"
        , exceptions = "exceptions_numerator"
    ) %>%
    select(-ends_with("_numerator"), -ends_with("_denominator")) %>%
    mutate(
        suboptimal = denominator - optimal
        # at some point attach a modelled value
        , model = 0
        # when patients reports as excepted, but included anyway ... National RA
        # seems a bother
        , exceptions__effective = pmax(pmin(register - denominator, exceptions), 0)
        , exclusions = register - denominator - exceptions__effective
        # where there is no register .. reconstruct
        , register__effective = denominator + exceptions
        , exclusions__effective = 0
    ) %>%
    # substitute the effective bits
    mutate(
        register = ifelse(
            is.na(register), register__effective, register
        )
        , exclusions = ifelse(
            is.na(exclusions), exclusions__effective, exclusions
        )
        , exceptions = ifelse(
            !is.na(exceptions__effective), exceptions__effective, exceptions
        )
    ) %>%
    select(-ends_with("__effective")) %>%
    select(-denominator)

rm("register")

#
# for sorting stacked bars
#
# for each indicator attach ALL measures then filter those of interest
# - the register/listsize measures are to be attached to indicators by indicator group
# - where there is NO disease register, use indicator denominator for register, CAN prev denom. for listsize
# 
# 1. isolate performance indicators
# 2. isolate prevalence indicators
# 3. join prevalence indicators into performance by indicator_group
# 

# List of performance measures for each indicator
sb__lu_performance <- measures %>% 
    select(m.type, m.name, m.stat) %>%
    unique() %>%
    filter(
        m.type == "performance"
        , m.stat != "denominator"
    ) %>%
    mutate(measure_label = paste(m.name, sub("numerator", "count", m.stat))) %>%
    filter(!measure_label %in% c("achievement count"))


sb__measures__performance <- measures %>%
    filter(!indicator_code %in% lu__register_indicators) %>%
    merge(sb__lu_performance, by = c("m.type", "m.name", "m.stat"), all.x = FALSE) %>%
    select(
        ccg_code, practice_code
        , indicator_group_code
        , indicator_code
        , m.type, m.name, m.stat, value, measure_label
        , domain_code, qof_period
    )


# attach qofprevalance measure for group to all codes

# List of prevalence stats for register
sb__lu_prevalence <- measures %>%
    filter(m.name == "qofprevalence") %>%
    select(m.type, m.name, m.stat) %>% unique() %>%
    mutate(measure_label = paste(
        m.name
        , m.stat %>% 
            sub("numerator", "register", .) %>%
            sub("denominator", "listsize", .)
    ))

sb__lu <- list(
    sb__lu_performance
    , sb__lu_prevalence
) %>% rbindlist(use.names = TRUE)

# attach to all indicators
sb__measures__prevalence <- measures %>%
    # generate frame
    #filter(!indicator_code %in% lu__register_indicators) %>% 
    select(ccg_code, practice_code, indicator_group_code, indicator_code) %>%
    unique() %>%
    merge(sb__lu_prevalence, all.x = TRUE) %>%
    # merge in prevalence values
    merge(
        measures %>%
            select(-org.type, -display_order, -indicator_code) # , -domain_code)
        , by = c(
            "ccg_code", "practice_code"
            , "indicator_group_code"
            , "m.type", "m.name", "m.stat"
        )
        , all.x = TRUE
    )


sb__measures <- list(
    sb__measures__performance
    , sb__measures__prevalence
) %>%
    rbindlist(use.names = TRUE)

#
# For sorting heatmaps
#

hm__sort_options <- c("practice_code", "summary_measure")

```


About
====

Fila {.tabset}
-----------------------------------------------------------------------

### About

This dashboard investigates variation in QOF based on publically available QOF data.

### Introduction

QOF Data: NHS Digital QOF 16/17.

#### What is in QOF

QOF contains information about the quality of care provided by GP practices in England.
There are a number of domains within QOF, relating to different aspects of care, but for this report only the CLINICAL DOMAIN, relating to patient care, is considered.

The clinical domain contains information for separate DISEASE GROUPS.  It does not consider multimorbidity i.e. patients with one or more of these diseases.

Each disease group has a REGISTER of patients diagnosed with that disease.

Within each disease group are a number of INDICATORS relating to specific aspects of care for those patients.

Where the aspect of care refers to a subset of patients, e.g. those newly registered, then those other patients who are not in the subset will not be included in the indicator.  These are called EXCLUSIONS.

Where the aspect of care is relevant to a patient, but there is a recognised reason for the patient not to receive the aspect of care, e.g. informed dissent, medical contra-indication, then the patient is not included in the indicator.  Patients where this is the case are called EXCEPTIONS.

QOF reports are by:

- ccg, practice
- domain, group and indicator

Performance and prevalence is reported:

- prevalence by group
- performance by indicators


A disease group will have a REGISTER of patients.
Each indicator represents a particular aspect of care for those patients.



### Methodology

Statistical methods: based on PHE/APHO methodology.

Confidence level of 95% used for confidence intervals.

SPC limits taken to be 2 and 3 standard deviations.

Measures considered are:

- 


### Results


### Discussion



Heatmap
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show variation in QOF.

```{r heatmap_inputs}

bRenderD3 = FALSE
selectInput(
    "hm__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
    , selectize = FALSE
)

checkboxInput(
    "hm__bool_hide_practices"
    , label = "Hide practices"
    , value = FALSE
)

selectInput(
    "hm__this_ind_group"
    , label = "Select indicator group:"
    , choices = c("[All]", these_ind_groups)
    , selected = "[All]"
    , multi = TRUE
    , selectize = FALSE
)

selectInput(
    "hm__this_measure"
    , label = "Select measure:"
    , choices = these_measures
    , selected = "exceptions" # these_measures[1]
    , selectize = FALSE
)

selectInput(
    "hm__this_comparison_method"
    , label = "Select comparison method:"
    , choices = these_comparisons
    , selected = "spc" # these_comparisons[1]
    , selectize = FALSE
)

selectInput(
    "hm__this_comparator"
    , label = "Select comparator:"
    , choices = these_comparators
    , selected = "england" # these_comparators[1]
    , selectize = FALSE
)

selectInput(
    "hm__this_sort_option"
    , label = "Order practices by:"
    , choices = hm__sort_options
    #, selected = hm__sort_options[1]
    , selected = "summary_measure"
    , selectize = FALSE
)

# To implement at some point
# checkboxInput(
#     "hm__group_prac_by_ccg"
#     , label = "Group practices within CCG"
#     , value = FALSE
# )

checkboxInput(
    "hm__sort_desc"
    , label = "Reverse sort"
    , value = FALSE
)

if (bRenderD3) {
    
    checkboxInput("hm__group_rows", "Group rows", FALSE)
    checkboxInput("hm__group_cols", "Group cols", FALSE)
    
}

```

```{r heatmap_prepare_data}
hm__this_ccg_group <- reactive(input$hm__this_ccg_group)
hm__this_ind_group <- reactive(input$hm__this_ind_group)
hm__this_measure <- reactive(input$hm__this_measure)
hm__this_comparator <- reactive(input$hm__this_comparator)
hm__this_comparison_method <- reactive(input$hm__this_comparison_method)
hm__bool_hide_practices <- reactive(input$hm__bool_hide_practices)
hm__sort_desc <- reactive(input$hm__sort_desc)
hm__this_sort_option <- reactive(input$hm__this_sort_option)

hm__tmp_practices_list <- reactive({
    
    # For development
    l__this_ccg_group <- "Mid. Notts. UOP"
    l__bool_hide_practices <- FALSE
    
    l__this_ccg_group <- hm__this_ccg_group()
    l__bool_hide_practices <- hm__bool_hide_practices()
    
    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant ccg group ccgs
    relevant_ccg_group_ccgs <- lu.orgs.ccgs.groups %>%
        filter(
            ccg_group_name == l__this_ccg_group |
                ccg_code == l__this_ccg_group
        ) %>% .$ccg_code
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(ccg_code %in% relevant_ccg_group_ccgs) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (l__bool_hide_practices == FALSE) {
        relevant_practices <-
            practice_grouping %>%
            filter(ccg_group_name == l__this_ccg_group) %>%
            .$practice_code
    } else {
        relevant_practices <- c() # NULL
    }
    
    
    c(global_orgs, relevant_ccg_group_ccgs, relevant_orgs, relevant_practices) %>%
        unique() %>% invisible()
})

hm__heatmap_dat__ggplot <- reactive({

    l__this_ind_group <- hm__this_ind_group()
    l__this_measure <- hm__this_measure()
    l__this_comparator <- hm__this_comparator()
    l__this_comparison_method <- hm__this_comparison_method()
    l__tmp_practices_list <- hm__tmp_practices_list()
    l__hm__this_sort_option <- hm__this_sort_option()
    l__hm__sort_desc <- hm__sort_desc()
    
    this_dat <- compare %>%
        # filter on measure and comparison
        filter(
            m.name == l__this_measure
            , org.type.ref == l__this_comparator
            , compare.type == l__this_comparison_method
            , any(l__this_ind_group == "[All]") |
                indicator_group_code %in% l__this_ind_group
        ) %>%
        # filter on practices of interest
        filter(practice_code %in% l__tmp_practices_list) %>%
        mutate(
            ind_label = paste(indicator_group_code, indicator_code)
            , org_label = paste(ccg_code, practice_code)
        ) %>%
        select(display_order, ind_label, org_label, compare.param, statsig) %>%
        merge(lu_statsig_num, by = "statsig") %>%
        # this handles benchmark and spc    
        #dcast(ccg_code + practice_code ~ indicator_code, value.var = "istatsig", fun = sum)
        group_by_at(vars(-compare.param, -istatsig, -statsig)) %>%
        summarise_at(vars(istatsig), sum) %>%
        ungroup() %>%
        mutate(value_sort = 0)
    
    # Decide how to sort
    if (l__hm__this_sort_option == "summary_measure") {
        this_sort <- this_dat %>%
            #filter(!is.na(istatsig)) %>%
            group_by_at(vars(-ind_label, -istatsig)) %>%
            summarise_at(
                vars(istatsig)
                , funs(
                    m2 = sum(. < -1, na.rm = TRUE)
                    , m1 = sum(. == -1, na.rm = TRUE)
                    , z = sum(. == 0, na.rm = TRUE)
                    , p1 = sum(. == 1, na.rm = TRUE)
                    , p2 = sum(. > 1, na.rm = TRUE)
                    , na = sum(is.na(.))
                )
            ) %>%
            ungroup() %>%
            mutate(n = m2 + m1 + z + p1 + p2 + na) %>%
            # Lots of ways of doing this - this is reasonable
            #mutate(value_sort = -(4*m2 + 2*m1 + 0*(z + na) - 2*p1 - 4*p2) / n)
            #mutate(value_sort = -(1*m2 + 1*m1 + 0*(z + na) - 1*p1 - 1*p2) / n)
            #mutate(value_sort = -(2*m2 + 1*m1 + 0*(z + na) - 1*p1 - 2*p2) / n)
            mutate(value_sort = (3*m2 + 2*m1 + 0*(z + na) - 2*p1 - 3*p2) / n)
    } else {
        this_sort <- this_dat %>%
            #filter(!is.na(istatsig)) %>%
            select_at(vars(-ind_label, -istatsig)) %>%
            unique() %>%
            mutate(value_sort = 0)
    }

    # to add sort methods
    if (l__hm__sort_desc == TRUE) {
        orgs_ordered <- this_sort %>%
            arrange(display_order, desc(value_sort), desc(org_label)) %>%
            .$org_label %>% unique()
    } else {
        orgs_ordered <- this_sort %>%
            arrange(display_order, value_sort, org_label) %>%
            .$org_label %>% unique()
    }
    
    retval <- list(
        this_dat
        , this_sort
    ) %>% lapply(
        function(x, y) {
            mutate(x, org_label_ordered = ordered(org_label, levels = rev(y)))
        }
        , orgs_ordered
    ) %>% {
        list(
            heatmap = .[[1]]
            , sort_summary = .[[2]]
            , sort_summary_melt = .[[2]] %>%
                melt(measure.vars = c("m2", "m1", "zm", "na", "zp", "p1", "p2"))
        )
    }
    
    retval %>% invisible()
})


```

Fila
-----------------------------------------------------------------------

### Heatmap and Summary

```{r heatmap_and_summary}

renderPlot({
    hm__data <- hm__heatmap_dat__ggplot()
    
    hm__data_heatmap <- hm__data$heatmap
    
    require("ggplot2")
    require("ggpubr")
    
    p__base_size <- 12
    
    p <- ggplot(
        hm__data_heatmap
        #, aes(x = indicator_code, y = practice_code)
        , aes(x = ind_label, y = org_label_ordered)
    ) + 
        geom_tile(aes(fill = istatsig), colour = "white") + 
        #scale_fill_gradient(low = "white", high = "steelblue") +
        #    this_col = colorRampPalette(c("#6666cc", "#ffffee", "#cc8888"), space = "Lab")(5)
        scale_fill_gradient2(
            low = "#6666cc"
            , mid = "#ffffee"
            , high = "#cc8888"
            , na.value = "#cccccc"
            , space = "Lab") +
        # styling
        theme_grey(base_size = p__base_size) + 
        labs(x = "", y = "", fill = "Level of variation (-2 low, +2 high)") + 
        scale_x_discrete(expand = c(0, 0), position = "top") +
        scale_y_discrete(expand = c(0, 0)) +
        theme(
            #legend.position = "none"
            legend.position = "top"
            , axis.ticks = element_blank()
            , axis.text.x = element_text(
                size = max(7, p__base_size * 0.67)
                , angle = 60 # 45 30
                , hjust = 0
                , colour = "grey50"
            )
        )
if (bRenderD3) {
    
    hm__this_group_rows <- reactive(input$hm__group_rows)
    hm__this_group_cols <- reactive(input$hm__group_cols)
    hm__data_summary <- hm__data$sort_summary_melt
    
    hm__heatmap_dat__d3 <- reactive({
        this_dat <- compare %>%
            # filter on measure and comparison
            filter(
                m.name == hm__this_measure()
                , org.type.ref == hm__this_comparator()
                , compare.type == hm__this_comparison_method()
            ) %>%
            # filter on practices of interest
            filter(practice_code %in% hm__tmp_practices_list()) %>%
            mutate(
                xticklabel = paste(indicator_group_code, indicator_code)
                , yticklabel = paste(ccg_code, practice_code)
            ) %>%
            #select(ccg_code, practice_code, indicator_code, compare.param, statsig) %>%
            select(xticklabel, yticklabel, compare.param, statsig) %>%
            merge(lu_statsig_num, by = "statsig") %>%
            # this handles benchmark and spc    
            dcast(xticklabel ~ yticklabel, value.var = "istatsig", fun = sum)
        
        rownames(this_dat) <- this_dat %>%
            select(xticklabel)
        
        this_dat <- this_dat %>% select(-ends_with("_code"))
        
        this_dat %>% invisible()
        
    })
    # blue to red through yellow
    this_col = colorRampPalette(c("#6666cc", "#ffffee", "#cc8888"), space = "Lab")(5)
    cols <- c(
        m2 = this_col[1]
        , m1 = this_col[2]
        , zm = this_col[3]
        , na = "#dddddd"
        , zp = this_col[3]
        , p1 = this_col[4]
        , p2 = this_col[5]
    )
    
    renderD3heatmap({
        # prepare matrix from reactive() components
        
        # ... and plot
        
        #this_col = colorRampPalette(c("blue", "yellow", "red"), space = "Lab")(5)
        #this_col = "RdYlBu"
        this_col = colorRampPalette(c("#6666cc", "#ffffee", "#cc8888"), space = "Lab")(5)
        this_idendrogram <- c(hm__this_group_rows(), hm__this_group_cols()) %*% c(1, 2) + 1
        #this_idendrogram <- c(input$group_rows, input$group_cols) %*% c(1, 2) + 1
        
        dendrogram_opts <- c("none", "row", "column", "both")
        
        #print(dendrogram_opts[this_idendrogram])
        
        d3heatmap(
            hm__heatmap_dat__d3()
            , colors = this_col
            , dendrogram = dendrogram_opts[this_idendrogram]
    p2 <- ggplot(hm__data_summary) +
        geom_col(
            aes(
                x = org_label_ordered
                , y = value
                , fill = variable
            )
            , position = position_fill(reverse = TRUE)
            #, position = position_stack(reverse = TRUE)
        ) +
        coord_flip() + 
        scale_fill_manual(values = cols) +
        #scale_y_continuous(labels = scales::percent) +
        scale_y_reverse(expand = c(0, 0)) +
        #scale_y_continuous(expand = c(0, 0)) +
        labs(x = "", y = "") + 
        theme_grey() +
        theme(legend.position = "none") + 
        #theme(legend.position = "top") +
        theme(
            #legend.position = "none"
            axis.ticks = element_blank()
            , axis.text.x = element_blank()
        )
    })
}
    
    
    ggarrange(
        p, p2, widths = c(3,1), align = "h", common.legend = TRUE
    )
})

```

Stacked bars
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show QOF dat for practice.

```{r stackedbar_input}

selectInput(
    "sb__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
)

checkboxInput(
    "sb__bool_hide_practices"
    , "Hide practices"
    , FALSE
)

selectInput(
    "sb__this_practice"
    , label = "Select Practice:"
    , choices = c("[All]", these_practices)
    #, selected = these_practices[1]
    , selected = "[All]"
)

selectInput(
    "sb__this_indicator"
    , label = "Select indicator:"
    , choices = c("[All]", these_indicators_noregister)
    , selected = these_indicators_noregister[1]
    #, selected = "[All]"
)

selectInput(
    "sb__this_sort_measure"
    , label = "Order practices by:"
    , choices = sb__lu$measure_label
    #, selected = sb__lu$measure_label[1]
    , selected = "exceptions value"
)

checkboxInput(
    "sb__sort_desc"
    , label = "Sort descending"
    , value = TRUE
)

checkboxInput(
    "sb__scale_counts_largest_gp"
    , label = "For GPs scale counts to largest overall GP register"
    , value = FALSE
)

sb__this_ccg_group <- reactive(input$sb__this_ccg_group)
sb__this_practice <- reactive(input$sb__this_practice)
sb__bool_hide_practices <- reactive(input$sb__bool_hide_practices)
sb__this_indicator <- reactive(input$sb__this_indicator)
sb__this_sort_measure <- reactive(input$sb__this_sort_measure)
sb__this_sort_desc <- reactive(input$sb__sort_desc)
sb__scale_counts_largest_gp <- reactive(input$sb__scale_counts_largest_gp)

sb__tmp_practices_list <- reactive({
    
    l__this_practice <- sb__this_practice()
    l__bool_hide_practices <- sb__bool_hide_practices()
    l__this_ccg_group <- sb__this_ccg_group()
    
    # For debugging dynamic elements
    #
    # l__this_practice <- "C84001"
    # l__this_ccg_group <- "02Q"
    # l__this_ccg_group <- "Mid. Notts. UOP"
    
    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant ccg group ccgs
    relevant_ccg_group_ccgs <- lu.orgs.ccgs.groups %>%
        filter(
            ccg_group_name == l__this_ccg_group |
                ccg_code == l__this_ccg_group
        ) %>% .$ccg_code
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(ccg_code %in% relevant_ccg_group_ccgs) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (l__bool_hide_practices == FALSE) {
        if (l__this_practice == "[All]") {
            relevant_practices <-
                practice_grouping %>%
                filter(ccg_group_name == l__this_ccg_group) %>%
                .$practice_code
        } else {
            relevant_practices <- l__this_practice
        }
    } else {
        relevant_practices <- c() # NULL
    }
    
    
    c(global_orgs, relevant_ccg_group_ccgs, relevant_orgs, relevant_practices) %>%
        unique() %>% invisible()
})

```

Fila
-----------------------------------------------------------------------

### Stacked Bar

```{r stackedbar}

sb__ind_dat <- reactive({
    
    # For debugging dynamic elements
    
    l__this_indicator <- "CHD005" # "AF006"
    l__this_practice <- "C84001"
    l__bool_hide_practices <- FALSE
    l__tmp_practices_list <- c("eng", "n2", "02Q", "C84001", "C84008", "C84013")
    l__this_sort_measure <- "exceptions value"
    l__sort_desc = TRUE
    l__sb__scale_counts_largest_gp <- TRUE # FALSE
    
    l__this_indicator <- sb__this_indicator()
    l__this_practice <- sb__this_practice()
    l__bool_hide_practices <- sb__bool_hide_practices()
    l__tmp_practices_list <- sb__tmp_practices_list()
    l__this_sort_measure <- sb__this_sort_measure()
    l__sort_desc <- sb__this_sort_desc()
    l__sb__scale_counts_largest_gp <- sb__scale_counts_largest_gp()
    
    l__this_ccg <- orgref %>%
        filter(practice_code == l__this_practice) %>%
        .$ccg_code
    
    l__this_ind_group <- indmap %>%
        filter(indicator_code == l__this_indicator) %>%
        .$indicator_group_code
    
    l__sort_measure <- sb__measures %>%
        filter(
            practice_code %in% l__tmp_practices_list
            , indicator_code == l__this_indicator
            , measure_label == l__this_sort_measure
        )
    
    l_ind <- counts %>%
        filter(
            practice_code %in% l__tmp_practices_list
            , indicator_code == l__this_indicator
        ) %>% merge(
            l__sort_measure %>%
                select(-starts_with("m"), -indicator_group_code, value_sort = value)
            , by = c("ccg_code", "practice_code", "indicator_code")
            # reverse value if descending
        ) %>%
        mutate(value_sort = (2 * (!l__sort_desc) - 1) * value_sort) %>%
        # add org_label
        mutate(org_label = paste(ccg_code, practice_code))
    
    fields_ordered <- c(
        "optimal"
        , "suboptimal"
        , "exceptions"
        , "exclusions"
        , "model"
    )
    
    orgs_ordered <- l_ind %>%
        arrange(display_order, value_sort) %>%
        .$org_label
    
    l_ind_melt <- l_ind %>%
        select(-value_sort) %>%
        setDT() %>%
        melt(
            measure.vars = fields_ordered
            , variable.name = "status", variable.factor = FALSE
            , value.name = "value", value.factor = FALSE
        ) %>%
        mutate(pvalue = value / register) %>%
        # dark arts to get desired order ...
        mutate_at(vars(status), ordered, levels = fields_ordered) %>%
        mutate(
            org_label_ordered = ordered(org_label, levels = rev(orgs_ordered))
        )
    
    if (l__sb__scale_counts_largest_gp == TRUE) {
        # find largest GP register ... then scale all GPs by that value
        register_max <- l_ind %>%
            filter(practice_code %like% "[CY].....") %>%
            .$register %>% max()
        
        l_ind_melt <- l_ind_melt %>%
            mutate(pvalue = ifelse(
                practice_code %like% "[CY]....."
                , value / register_max
                , pvalue)
            )
    }
    
    l_ind_melt %>% invisible()
})

renderPlot({
    
    cols <- c(
        optimal = "green4"
        , suboptimal = "darkorange"
        , exceptions = "red"
        , exclusions = "lightblue"
        , model = "gray50"
    )
    
    l_ind_melt <- sb__ind_dat()
    
    p <- ggplot(l_ind_melt) +
        geom_col(
            aes(
                x = org_label_ordered
                , y = pvalue
                , fill = status
            )
            , position = position_stack(reverse = TRUE)
        ) +
        geom_text(
            data = subset(l_ind_melt, value > 0)
            , aes(
                x = org_label_ordered
                , y = pvalue
                , label = ifelse(
                    status %in% c("optimal", "exceptions", "model")
                    , scales::comma(value)
                    , ""
                )
            )
            , position = position_stack(vjust = 0.5)
            , size = 3
        ) +
        #scale_colour_manual(values = cols, aesthetics = "fill") +
        scale_fill_manual(values = cols) +
        coord_flip() +
        scale_y_continuous(labels = scales::percent) +
        theme_minimal() +
        theme(legend.position = "top") +
        labs(x = "", y = "Counts scaled relative to register (percent)")
    
    if (sb__scale_counts_largest_gp() == TRUE)
        p <- p + labs(
            y = "Counts scaled relative to largest GP register overall (percent)"
        ) 
    
    p %>% print()
    
})

```


Practice detail
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show QOF dat for practice.

```{r practicedetail_input}

selectInput(
    "pd__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
)

selectInput(
    "pd__this_practice"
    , label = "Select Practice:"
    , choices = c("[All]", these_practices)
    #, selected = these_practices[1]
    , selected = "[All]"
)

selectInput(
    "pd__this_ind_group"
    , label = "Select indicator group:"
    , choices = c("[All]", these_ind_groups)
    #, selected = these_ind_groups[1]
    , selected = "[All]"
)

selectInput(
    "pd__this_measure"
    , label = "Select measure:"
    , choices = c("[All]", these_measures)
    , selected = "exceptions"
)

pd__this_ccg_group <- reactive(input$pd__this_ccg_group)
pd__this_practice <- reactive(input$pd__this_practice)
pd__this_measure <- reactive(input$pd__this_measure)
pd__this_ind_group <- reactive(input$pd__this_ind_group)

pd__tmp_practices_list <- reactive({
    # # practices
    # if (pd__this_practice() == "[All]") {
    #     practice_grouping %>%
    #         filter(ccg_group_name == pd__this_ccg_group()) %>%
    #         select(practice_code) %>% unlist() %>% as.vector()
    # } else {
    #     pd__this_practice()
    # }
    
    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(
            ccg_code %in% 
                (lu.orgs.ccgs.groups %>% filter(
                    ccg_group_name == pd__this_ccg_group() |
                        ccg_code == pd__this_ccg_group()
                ) %>% .$ccg_code)
        ) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (pd__this_practice() == "[All]") {
        relevant_practices <-
            practice_grouping %>%
            filter(ccg_group_name == pd__this_ccg_group()) %>%
            #.$practice_code %>%
            select(practice_code) %>% unlist() %>% as.vector()
    } else {
        relevant_practices <- pd__this_practice()
    }
    
    
    c(global_orgs, relevant_orgs, relevant_practices) %>% unique() %>% invisible()
})

```


Practice detail {.tabset}
----

### compare

```{r practicedetail_compare}
#cat("DEBUG: compare:", taskdir, "\n")
#compare %>% mutate_if(is.character, as.factor) %>% str()
#compare %>% mutate_if(is.character, as.factor) %>% summary()

pd__compare_dat <- reactive({
    compare %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
            , (pd__this_ind_group() == "[All]") | (indicator_group_code == pd__this_ind_group())
            , (pd__this_measure() == "[All]") | (m.name == pd__this_measure())
        ) %>%
        select(-org.type.var, -m.type) %>%
        select(ccg_code, practice_code, indicator_group_code, indicator_code, org.type.ref, everything()) %>%
        dcast(... ~ compare.type + compare.param, value.var = "statsig", fun = function(x){paste(x, collapse = "")}) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__compare_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pageLength = 16
        )
    )
})


```

### measures

```{r practicedetail_measures}
#cat("DEBUG: measures:", taskdir, "\n")

pd__measures_dat <- reactive({
    measures %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
            , (pd__this_ind_group() == "[All]") | (indicator_group_code == pd__this_ind_group())
            , (pd__this_measure() == "[All]") | (m.name == pd__this_measure())
        ) %>%
        select(-org.type, -m.type) %>%
        select(ccg_code, practice_code, indicator_group_code, indicator_code, everything()) %>%
        dcast(... ~ m.stat, fun = sum) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__measures_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pageLength = 16
        )
    ) %>%
        DT::formatRound(c("numerator", "denominator"), digits = 0) %>%
        DT::formatRound("value", digits = 1)
})

```

### orgref

```{r practicedetail_orgref}
#cat("DEBUG: orgref:", taskdir, "\n")
#orgref %>% mutate_if(is.character, as.factor) %>% str()
#orgref %>% mutate_if(is.character, as.factor) %>% summary()

pd__orgref_dat <- reactive({
    orgref %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
        ) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__orgref_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pagelength = 16
        )
    )
})
```

### indmap

```{r practicedetail_indmap}
#cat("DEBUG: indmap:", taskdir, "\n")
#indmap %>% mutate_if(is.character, as.factor) %>% str()
#indmap %>% select(-ends_with("description")) %>% mutate_if(is.character, as.factor) %>% summary()

pd__indmap_dat <- reactive({
    indmap %>% 
        filter(
            pd__this_ind_group() == "[All]" | 
                indicator_group_code == pd__this_ind_group()
        ) %>%
        select(-indicator_group_code) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__indmap_dat() %>% setnames.display()
        , class = "compact"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pagelength = 16
        )
    )
})

```



Debug
====

Debug {.tabset}
----

### Debug

``` {r debug_overview}
#cat("DEBUG: getwd =", getwd(), "\n")
#cat("DEBUG: taskdir =", taskdir, "\n")
```

### compare

```{r debug_compare}
#cat("DEBUG: compare:", taskdir, "\n")
compare %>% mutate_if(is.character, as.factor) %>% str()
compare %>% mutate_if(is.character, as.factor) %>% summary()

```

### measures

```{r debug_measures}
#cat("DEBUG: measures:", taskdir, "\n")
measures %>% mutate_if(is.character, as.factor) %>% str()
measures %>% mutate_if(is.character, as.factor) %>% summary()

```

### orgref

```{r debug_orgref}
#cat("DEBUG: orgref:", taskdir, "\n")
orgref %>% mutate_if(is.character, as.factor) %>% str()
orgref %>% mutate_if(is.character, as.factor) %>% summary()

```

### indmap

```{r debug_indmap}
#cat("DEBUG: indmap:", taskdir, "\n")
indmap %>% mutate_if(is.character, as.factor) %>% str()
indmap %>% select(-ends_with("description")) %>% mutate_if(is.character, as.factor) %>% summary()

```

