---
title: "QOF variation dashboard"
author: "Ian Bates"
output: 
    flexdashboard::flex_dashboard:
    orientation: rows
    source_code: embed
#    vertical_layout: fill # scroll
    vertical_layout: scroll
    runtime: shiny
---

```{r setup, include = FALSE, cache = FALSE}
require("flexdashboard")
require("shiny")
#require("d3heatmap")
require("DT")

knitr::opts_chunk$set(cache = FALSE)
knitr::opts_chunk$set(echo = FALSE)

```

```{r global, include = FALSE, cache = TRUE}
# load data in 'global' chunk so it can be shared by all users of the dashboard

taskdir <- normalizePath("..")
source(file = paste(taskdir, "Analysis/main.R", sep = "/"))
#source(file = paste(taskdir, "Analysis/cdg_91_qof.R", sep = "/"))

#dat <- main(qof_period = "1516", bProcessRaw = FALSE, bLoadData = FALSE)
dat <- main(qof_period = "1617", bProcessRaw = FALSE, bLoadData = FALSE)

l_add_orgtag <- function(x, c1 = "ccg_code", c2 = "practice_code") {
    x %>%
        mutate(
            orgtag = paste(
                UQ(rlang::sym(c1))
                , UQ(rlang::sym(c2))
            )
        ) %>% invisible()
}

# Add ccg group lookup
lu.orgs.ccgs.groups <- fread(
    file = paste_paths(taskdir, "./Results/lu__ccg_groups.csv")
) #%>% l_add_orgtag("ccg_group_type", "ccg_group_code")

# Add display order
#
# Based on ccg_group_type.  
# Manually add CCGs go to 10, practices go to 20.
l_add_display_order <- function(x, c1 = "org.type") {
    x %>% 
        merge(
            lu.orgs.ccgs.groups %>% 
                select(ccg_group_code, display_order = type_display_order) %>%
                unique()
            , by.x = "practice_code", by.y = "ccg_group_code"
            , all.x = TRUE
        ) %>%
        mutate(display_order = ifelse(UQ(rlang::sym(c1)) == "england", 0, display_order)) %>%
        mutate(display_order = ifelse(UQ(rlang::sym(c1)) == "ccg::instance", 10, display_order)) %>%
        mutate(display_order = ifelse(is.na(display_order), 20, display_order))
}

setnames.display <- function(x) {setnames(x, gsub("_|\\.", " ", names(x)))}

# actually load data
orgref <- dat$reference$orgref #%>% l_add_orgtag()
indmap <- dat$reference$indmap
measures <- dat$measures %>% l_add_display_order() #%>% l_add_orgtag()
compare <- dat$compare %>% l_add_display_order("org.type.var") #%>% l_add_orgtag()

practice_grouping <- list(
    orgref %>% 
        # filter out existing ccg groups
        filter(nchar(practice_code) > 3) %>%
        select(practice_code, ccg_code) %>%
        merge(lu.orgs.ccgs.groups, by = "ccg_code", all.y = TRUE) %>%
        select(-type_display_order)
    
    , orgref %>% 
        # filter out existing ccg groups
        filter(nchar(practice_code) > 3) %>%
        # only local ccgs
        filter(ccg_code %in% c(lu.orgs.ccgs.groups$ccg_code %>% unique())) %>%
        select(practice_code, ccg_code) %>%
        mutate(
            ccg_group_type = "ccg"
            , ccg_group_type_name = "ccg"
            , ccg_group_code = ccg_code
            , ccg_group_name = ccg_code
        )
) %>%
    # lapply(function(x){sort(names(x))}) 
    rbindlist(use.names = TRUE)

# For inputs

these_orgtypes <- measures$org.type %>% unique() %>% sort()
these_ccg_groups <- practice_grouping$ccg_group_name %>% unique() %>% sort()
these_ccgs <- measures$ccg_code %>% unique() %>% sort()
these_practices <- practice_grouping$practice_code %>% unique() %>% sort()

these_ind_groups <- measures$indicator_group_code %>% unique() %>% sort()
these_indicators <- measures$indicator_code %>% unique() %>% sort()

these_measures <- measures$m.name %>% unique() %>% sort()

these_comparisons <- compare$compare.type %>% unique() %>% sort()
these_comparisons_param <- compare$compare.param  %>% unique() %>% sort()

these_comparators <- compare$org.type.ref %>% unique() %>% sort()


# for e.g. Heatmap

lu_statsig_num <- fread(input = "
statsig,istatsig
Better,1
Higher,1
Similar,0
Lower,-1
Worse,-1
Not tested,NA
"
)

# for stacked bar

register <- measures %>%
    filter(
        m.type == "prevalence"
        , m.name == "qofprevalence"
        , m.stat == "numerator"
    ) %>%
    select(-m.type, -m.name) %>%
    dcast(... ~ m.stat) %>%
    rename(register = "numerator") %>%
    select(
        ccg_code, practice_code, indicator_group_code
        , register
    )

counts <- measures %>%
    filter(
        m.type == "performance"
        , m.stat %in% c("numerator", "denominator")
    ) %>%
    select(-m.type, -org.type, -data_source) %>%
    dcast(... ~ m.name + m.stat) %>%
    merge(
        register
        , by = c("ccg_code", "practice_code", "indicator_group_code")
        , all.x = TRUE
    ) %>%
    rename(
        denominator = "achievement_denominator"
        , optimal = "treatment_numerator"
        , exceptions = "exceptions_numerator"
    ) %>%
    select(-ends_with("_numerator"), -ends_with("_denominator")) %>%
    mutate(
        suboptimal = denominator - optimal
        # at some point attach a modelled value
        , model = 0
        # when patients reports as excepted, but included anyway ... National RA seems a bother
        , exceptions__effective = pmax(pmin(register - denominator, exceptions), 0)
        , exclusions = register - denominator - exceptions__effective
        # where there is no register .. reconstruct
        , register__effective = denominator + exceptions
        , exclusions__effective = 0
    ) %>%
    # substitute the effective bits
    mutate(
        register = ifelse(is.na(register), register__effective, register)
        , exclusions = ifelse(is.na(exclusions), exclusions__effective, exclusions)
        , exceptions = ifelse(!is.na(exceptions__effective), exceptions__effective, exceptions)
    ) %>%
    select(-ends_with("__effective")) %>%
    select(-denominator)

rm("register")

# for sorting stacked bars

# measures %>% filter(practice_code %in% l__tmp_practices_list) %>% filter(m.stat != "denominator") %>% dcast(... ~ m.name + m.stat)
sb__lu_measures <- measures %>% 
    select(m.type, m.name, m.stat) %>%
    unique() %>%
    filter(m.stat != "denominator") %>%
    mutate(measure_label = paste(m.name, sub("numerator", "count", m.stat))) %>%
    filter(!measure_label %in% c("achievement count"))

sb__measures <- measures %>%
    merge(sb__lu_measures, by = c("m.type", "m.name", "m.stat"), all.x = FALSE) %>%
    select(
        ccg_code, practice_code
        , indicator_group_code, indicator_code
        , m.name, m.stat, value, measure_label
    )

```


Heatmap
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show variation in QOF.

```{r heatmap_inputs}

bRenderD3 = FALSE
bRenderggplot = TRUE
cat("INFO: possible input selections here", "\n")


selectInput(
    "hm__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
)

checkboxInput(
    "hm__bool_hide_practices"
    , "Hide practices"
    , FALSE
)

selectInput(
    "hm__this_ind_group"
    , label = "Select indicator group:"
    , choices = c("[All]", these_ind_groups)
    , selected = "[All]"
    , multi = TRUE
)

selectInput(
    "hm__this_measure"
    , label = "Select measure:"
    , choices = these_measures
    , selected = "exceptions" # these_measures[1]
)

selectInput(
    "hm__this_comparison_method"
    , label = "Select comparison method:"
    , choices = these_comparisons
    , selected = "spc" # these_comparisons[1]
)

selectInput(
    "hm__this_comparator"
    , label = "Select comparator:"
    , choices = these_comparators
    , selected = "england" # these_comparators[1]
)

if (bRenderD3) {
    
    checkboxInput("hm__group_rows", "Group rows", FALSE)
    checkboxInput("hm__group_cols", "Group cols", FALSE)
    
}

```


Row
-----------------------------------------------------------------------

### Heatmap

```{r heatmap_render}

#cat("INFO: Heatmap", "\n")

hm__this_ccg_group <- reactive(input$hm__this_ccg_group)
hm__this_ind_group <- reactive(input$hm__this_ind_group)
hm__this_measure <- reactive(input$hm__this_measure)
hm__this_comparator <- reactive(input$hm__this_comparator)
hm__this_comparison_method <- reactive(input$hm__this_comparison_method)
hm__bool_hide_practices <- reactive(input$hm__bool_hide_practices)

hm__tmp_practices_list <- reactive({
    
    l__this_ccg_group <- hm__this_ccg_group()
    l__bool_hide_practices <- hm__bool_hide_practices()
    
    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant ccg group ccgs
    relevant_ccg_group_ccgs <- lu.orgs.ccgs.groups %>%
        filter(
            ccg_group_name == l__this_ccg_group |
                ccg_code == l__this_ccg_group
        ) %>% .$ccg_code
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(ccg_code %in% relevant_ccg_group_ccgs) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (l__bool_hide_practices == FALSE) {
        relevant_practices <-
            practice_grouping %>%
            filter(ccg_group_name == l__this_ccg_group) %>%
            .$practice_code
    } else {
        relevant_practices <- c() # NULL
    }
    

    c(global_orgs, relevant_ccg_group_ccgs, relevant_orgs, relevant_practices) %>%
        unique() %>% invisible()
})


if (bRenderggplot) {
    
    hm__heatmap_dat__ggplot <- reactive({
        
        l__this_ind_group <- hm__this_ind_group()
        l__this_measure <- hm__this_measure()
        l__this_comparator <- hm__this_comparator()
        l__this_comparison_method <- hm__this_comparison_method()
        l__tmp_practices_list <- hm__tmp_practices_list()
        
        this_dat <- compare %>%
            # filter on measure and comparison
            filter(
                m.name == l__this_measure
                , org.type.ref == l__this_comparator
                , compare.type == l__this_comparison_method
                , any(l__this_ind_group == "[All]") |
                    indicator_group_code %in% l__this_ind_group
            ) %>%
            # filter on practices of interest
            filter(practice_code %in% l__tmp_practices_list) %>%
            mutate(
                ind_label = paste(indicator_group_code, indicator_code)
                , org_label = paste(ccg_code, practice_code)
            ) %>%
            select(display_order, ind_label, org_label, compare.param, statsig) %>%
            merge(lu_statsig_num, by = "statsig") %>%
            # this handles benchmark and spc    
            #dcast(ccg_code + practice_code ~ indicator_code, value.var = "istatsig", fun = sum)
            group_by_at(vars(-compare.param, -istatsig, -statsig)) %>%
            summarise_at(vars(istatsig), sum) %>%
            ungroup() %>%
            mutate(value_sort = 0)
        
        # to add sort methods
        orgs_ordered <- this_dat %>%
            arrange(display_order, value_sort, org_label) %>%
            .$org_label %>% unique()
        
        orgs_ordered %>% print()
        
        this_dat <- this_dat %>%
            # try to sort for plot
            mutate(
                org_label_ordered = ordered(org_label, levels = rev(orgs_ordered))
            )

        this_dat %>% invisible()
    })
    
    renderPlot({
        require("ggplot2")
        
        p__base_size <- 12
        
        p <- ggplot(
            hm__heatmap_dat__ggplot()
            #, aes(x = indicator_code, y = practice_code)
            , aes(x = ind_label, y = org_label_ordered)
        ) + 
            geom_tile(aes(fill = istatsig), colour = "white") + 
            #scale_fill_gradient(low = "white", high = "steelblue") +
            #    this_col = colorRampPalette(c("#6666cc", "#ffffee", "#cc8888"), space = "Lab")(5)
            scale_fill_gradient2(
                low = "#6666cc"
                , mid = "#ffffee"
                , high = "#cc8888"
                , na.value = "#eeeeee"
                , space = "Lab") +
            # styling
            theme_grey(base_size = p__base_size) + 
            labs(x = "", y = "") + 
            scale_x_discrete(
                expand = c(0, 0), position = "top"
            ) +
            scale_y_discrete(expand = c(0, 0)) +
            theme(
                legend.position = "none"
                , axis.ticks = element_blank()
                , axis.text.x = element_text(
                    size = max(7, p__base_size * 0.67)
                    , angle = 60 # 45 30
                    , hjust = 0
                    , colour = "grey50"
                )
            )
        
        p %>% print()
    })
    
}

if (bRenderD3) {
    
    hm__this_group_rows <- reactive(input$hm__group_rows)
    hm__this_group_cols <- reactive(input$hm__group_cols)
    
    hm__heatmap_dat__d3 <- reactive({
        this_dat <- compare %>%
            # filter on measure and comparison
            filter(
                m.name == hm__this_measure()
                , org.type.ref == hm__this_comparator()
                , compare.type == hm__this_comparison_method()
            ) %>%
            # filter on practices of interest
            filter(practice_code %in% hm__tmp_practices_list()) %>%
            mutate(
                xticklabel = paste(indicator_group_code, indicator_code)
                , yticklabel = paste(ccg_code, practice_code)
            ) %>%
            #select(ccg_code, practice_code, indicator_code, compare.param, statsig) %>%
            select(xticklabel, yticklabel, compare.param, statsig) %>%
            merge(lu_statsig_num, by = "statsig") %>%
            # this handles benchmark and spc    
            dcast(xticklabel ~ yticklabel, value.var = "istatsig", fun = sum)
        
        rownames(this_dat) <- this_dat %>%
            select(xticklabel)
        
        this_dat <- this_dat %>% select(-ends_with("_code"))
        
        this_dat %>% invisible()
        
    })
    
    renderD3heatmap({
        # prepare matrix from reactive() components
        
        # ... and plot
        
        #this_col = colorRampPalette(c("blue", "yellow", "red"), space = "Lab")(5)
        #this_col = "RdYlBu"
        this_col = colorRampPalette(c("#6666cc", "#ffffee", "#cc8888"), space = "Lab")(5)
        this_idendrogram <- c(hm__this_group_rows(), hm__this_group_cols()) %*% c(1, 2) + 1
        #this_idendrogram <- c(input$group_rows, input$group_cols) %*% c(1, 2) + 1
        
        dendrogram_opts <- c("none", "row", "column", "both")
        
        #print(dendrogram_opts[this_idendrogram])
        
        d3heatmap(
            hm__heatmap_dat__d3()
            , colors = this_col
            , dendrogram = dendrogram_opts[this_idendrogram]
        )
    })
}

```


Stacked bars
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show QOF dat for practice.

```{r stackedbar_input}

selectInput(
    "sb__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
)

checkboxInput(
    "sb__bool_hide_practices"
    , "Hide practices"
    , FALSE
)

selectInput(
    "sb__this_practice"
    , label = "Select Practice:"
    , choices = c("[All]", these_practices)
    #, selected = these_practices[1]
    , selected = "[All]"
)

selectInput(
    "sb__this_indicator"
    , label = "Select indicator:"
    , choices = c("[All]", these_indicators)
    , selected = these_indicators[1]
    #, selected = "[All]"
)

selectInput(
    "sb__this_sort_measure"
    , label = "Order practices by:"
    , choices = sb__lu_measures$measure_label
    #, selected = sb__lu_measures$measure_label[1]
    , selected = "exceptions value"
)

checkboxInput(
    "sb__sort_desc"
    , label = "Sort descending"
    , value = TRUE
)

sb__this_ccg_group <- reactive(input$sb__this_ccg_group)
sb__this_practice <- reactive(input$sb__this_practice)
sb__bool_hide_practices <- reactive(input$sb__bool_hide_practices)
sb__this_indicator <- reactive(input$sb__this_indicator)
sb__this_sort_measure <- reactive(input$sb__this_sort_measure)
sb__this_sort_desc <- reactive(input$sb__sort_desc)

sb__tmp_practices_list <- reactive({
    
    l__this_practice <- sb__this_practice()
    l__bool_hide_practices <- sb__bool_hide_practices()
    l__this_ccg_group <- sb__this_ccg_group()
    
    # For debugging dynamic elements
    #
    # l__this_practice <- "C84001"
    # l__this_ccg_group <- "02Q"
    # l__this_ccg_group <- "Mid. Notts. UOP"

    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant ccg group ccgs
    relevant_ccg_group_ccgs <- lu.orgs.ccgs.groups %>%
        filter(
            ccg_group_name == l__this_ccg_group |
                ccg_code == l__this_ccg_group
        ) %>% .$ccg_code
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(ccg_code %in% relevant_ccg_group_ccgs) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (l__bool_hide_practices == FALSE) {
        if (l__this_practice == "[All]") {
            relevant_practices <-
                practice_grouping %>%
                filter(ccg_group_name == l__this_ccg_group) %>%
                .$practice_code
        } else {
            relevant_practices <- l__this_practice
        }
    } else {
        relevant_practices <- c() # NULL
    }
    

    c(global_orgs, relevant_ccg_group_ccgs, relevant_orgs, relevant_practices) %>%
        unique() %>% invisible()
})

```

Row
-----------------------------------------------------------------------

### Stacked Bar

```{r stackedbar}

sb__ind_dat <- reactive({
    
    l__this_indicator <- sb__this_indicator()
    l__this_practice <- sb__this_practice()
    l__bool_hide_practices <- sb__bool_hide_practices()
    l__tmp_practices_list <- sb__tmp_practices_list()
    l__this_sort_measure <- sb__this_sort_measure()
    l__sort_desc <- sb__this_sort_desc()
    
    # For debugging dynamic elements
    #
    # l__this_indicator <- "AF006"
    # l__this_practice <- "C84001"
    # l__tmp_practices_list <- c("eng", "n2", "02Q", "C84001", "C84008", "C84013")
    # l__this_sort_measure <- "exceptions value"
    # l__sort_desc = TRUE
    
    l__this_ccg <- orgref %>%
        filter(practice_code == l__this_practice) %>%
        .$ccg_code
    
    l__this_ind_group <- indmap %>%
        filter(indicator_code == l__this_indicator) %>%
        .$indicator_group_code
    
    l__sort_measure <- sb__measures %>%
        filter(
            practice_code %in% l__tmp_practices_list
            , indicator_code == l__this_indicator
            , measure_label == l__this_sort_measure
        )
    
    l_ind <- counts %>%
        filter(
            practice_code %in% l__tmp_practices_list
            , indicator_code == l__this_indicator
        ) %>% merge(
            l__sort_measure %>% select(-starts_with("m"), value_sort = value)
            , by = c("ccg_code", "practice_code", "indicator_code")
            # reverse value if descending
        ) %>%
        mutate(value_sort = (2 * (!l__sort_desc) - 1) * value_sort) %>%
        # add org_label
        mutate(org_label = paste(ccg_code, practice_code))
    
    fields_ordered <- c(
        "optimal"
        , "suboptimal"
        , "exceptions"
        , "exclusions"
        , "model"
    )
    
    orgs_ordered <- l_ind %>%
        arrange(display_order, value_sort) %>%
        .$org_label
    
    l_ind_melt <- l_ind %>%
        select(-value_sort) %>%
        setDT() %>%
        melt(
            measure.vars = fields_ordered
            , variable.name = "status", variable.factor = FALSE
            , value.name = "value", value.factor = FALSE
        ) %>%
        mutate(pvalue = value / register) %>%
        # dark arts to get desired order ...
        mutate_at(vars(status), ordered, levels = fields_ordered) %>%
        mutate(
            org_label_ordered = ordered(org_label, levels = rev(orgs_ordered))
        )
    
    l_ind_melt %>% invisible()
})

renderPlot({
    
    cols <- c(
        optimal = "green4"
        , suboptimal = "darkorange"
        , exceptions = "red"
        , exclusions = "lightblue"
        , model = "gray50"
    )
    
    l_ind_melt <- sb__ind_dat()
    
    p <- ggplot(l_ind_melt) +
        geom_col(
            aes(
                x = org_label_ordered
                , y = pvalue
                , fill = status
            )
            , position = position_stack(reverse = TRUE)
        ) +
        geom_text(
            data = subset(l_ind_melt, value > 0)
            , aes(
                x = org_label_ordered
                , y = pvalue
                , label = ifelse(
                    status %in% c("optimal", "exceptions", "model")
                    , scales::comma(value)
                    , ""
                )
            )
            , position = position_stack(vjust = 0.5)
            , size = 3
        ) +
        #scale_colour_manual(values = cols, aesthetics = "fill") +
        scale_fill_manual(values = cols) +
        coord_flip() +
        scale_y_continuous(labels = scales::percent) +
        labs(x = "", y = "Counts relative to register (percent)") + 
        theme_minimal() +
        theme(legend.position = "top")

    p %>% print()
    
})


cat("INFO: tab 1", "\n")

```


Practice detail
====

Inputs {.sidebar}
-----------------------------------------------------------------------

Show QOF dat for practice.

```{r practicedetail_input}

selectInput(
    "pd__this_ccg_group"
    , label = "Select Practice grouping:"
    , choices = these_ccg_groups
    , selected = these_ccg_groups[1]
)

selectInput(
    "pd__this_practice"
    , label = "Select Practice:"
    , choices = c("[All]", these_practices)
    #, selected = these_practices[1]
    , selected = "[All]"
)

selectInput(
    "pd__this_ind_group"
    , label = "Select indicator group:"
    , choices = c("[All]", these_ind_groups)
    #, selected = these_ind_groups[1]
    , selected = "[All]"
)

selectInput(
    "pd__this_measure"
    , label = "Select measure:"
    , choices = c("[All]", these_measures)
    , selected = "exceptions"
)

pd__this_ccg_group <- reactive(input$pd__this_ccg_group)
pd__this_practice <- reactive(input$pd__this_practice)
pd__this_measure <- reactive(input$pd__this_measure)
pd__this_ind_group <- reactive(input$pd__this_ind_group)

pd__tmp_practices_list <- reactive({
    # # practices
    # if (pd__this_practice() == "[All]") {
    #     practice_grouping %>%
    #         filter(ccg_group_name == pd__this_ccg_group()) %>%
    #         select(practice_code) %>% unlist() %>% as.vector()
    # } else {
    #     pd__this_practice()
    # }

    # every time
    global_orgs <- c("eng", "n2")
    
    # relevant orgs
    relevant_orgs <- 
        lu.orgs.ccgs.groups %>%
        filter(
            ccg_code %in% 
                (lu.orgs.ccgs.groups %>% filter(
                    ccg_group_name == pd__this_ccg_group() |
                        ccg_code == pd__this_ccg_group()
                ) %>% .$ccg_code)
        ) %>%
        .$ccg_group_code %>% unique()
    
    # practices
    if (pd__this_practice() == "[All]") {
        relevant_practices <-
            practice_grouping %>%
            filter(ccg_group_name == pd__this_ccg_group()) %>%
            #.$practice_code %>%
            select(practice_code) %>% unlist() %>% as.vector()
    } else {
        relevant_practices <- pd__this_practice()
    }
    
    c(global_orgs, relevant_orgs, relevant_practices) %>% unique() %>% invisible()

    
})

```


Practice detail {.tabset}
----

### compare

```{r practicedetail_compare}
#cat("DEBUG: compare:", taskdir, "\n")
#compare %>% mutate_if(is.character, as.factor) %>% str()
#compare %>% mutate_if(is.character, as.factor) %>% summary()

pd__compare_dat <- reactive({
    compare %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
            , (pd__this_ind_group() == "[All]") | (indicator_group_code == pd__this_ind_group())
            , (pd__this_measure() == "[All]") | (m.name == pd__this_measure())
        ) %>%
        select(-org.type.var, -data_source, -m.type) %>%
        select(ccg_code, practice_code, indicator_group_code, indicator_code, org.type.ref, everything()) %>%
        dcast(... ~ compare.type + compare.param, value.var = "statsig", fun = function(x){paste(x, collapse = "")}) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__compare_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pageLength = 16
        )
    )
})


```

### measures

```{r practicedetail_measures}
#cat("DEBUG: measures:", taskdir, "\n")

pd__measures_dat <- reactive({
    measures %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
            , (pd__this_ind_group() == "[All]") | (indicator_group_code == pd__this_ind_group())
            , (pd__this_measure() == "[All]") | (m.name == pd__this_measure())
        ) %>%
        select(-org.type, -data_source, -m.type) %>%
        select(ccg_code, practice_code, indicator_group_code, indicator_code, everything()) %>%
        dcast(... ~ m.stat, fun = sum) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__measures_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pageLength = 16
        )
    ) %>%
        DT::formatRound(c("numerator", "denominator"), digits = 0) %>%
        DT::formatRound("value", digits = 1)
})

```

### orgref

```{r practicedetail_orgref}
#cat("DEBUG: orgref:", taskdir, "\n")
#orgref %>% mutate_if(is.character, as.factor) %>% str()
#orgref %>% mutate_if(is.character, as.factor) %>% summary()

pd__orgref_dat <- reactive({
    orgref %>% 
        filter(
            practice_code %in% pd__tmp_practices_list()
        ) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__orgref_dat() %>% setnames.display()
        , class = "compact nowrap"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pagelength = 16
        )
    )
})
```

### indmap

```{r practicedetail_indmap}
#cat("DEBUG: indmap:", taskdir, "\n")
#indmap %>% mutate_if(is.character, as.factor) %>% str()
#indmap %>% select(-ends_with("description")) %>% mutate_if(is.character, as.factor) %>% summary()

pd__indmap_dat <- reactive({
    indmap %>% 
        filter(
            pd__this_ind_group() == "[All]" | 
            indicator_group_code == pd__this_ind_group()
        ) %>%
        select(-indicator_group_code, -data_source, -starts_with("domain_")) %>%
        mutate_if(is.character, as.factor) %>%
        invisible()
})

require("DT")

DT::renderDataTable({
    DT::datatable(
        pd__indmap_dat() %>% setnames.display()
        , class = "compact"
        , filter = list(position = 'top', clear = TRUE, plain = FALSE)
        , options = list(
            paging = TRUE, pagelength = 16
        )
    )
})

```



Debug
====

Debug {.tabset}
----

### Debug

``` {r debug_overview}
cat("DEBUG: getwd =", getwd(), "\n")
cat("DEBUG: taskdir =", taskdir, "\n")
```

### compare

```{r debug_compare}
cat("DEBUG: compare:", taskdir, "\n")
compare %>% mutate_if(is.character, as.factor) %>% str()
compare %>% mutate_if(is.character, as.factor) %>% summary()

```

### measures

```{r debug_measures}
cat("DEBUG: measures:", taskdir, "\n")
measures %>% mutate_if(is.character, as.factor) %>% str()
measures %>% mutate_if(is.character, as.factor) %>% summary()

```

### orgref

```{r debug_orgref}
cat("DEBUG: orgref:", taskdir, "\n")
orgref %>% mutate_if(is.character, as.factor) %>% str()
orgref %>% mutate_if(is.character, as.factor) %>% summary()

```

### indmap

```{r debug_indmap}
cat("DEBUG: indmap:", taskdir, "\n")
indmap %>% mutate_if(is.character, as.factor) %>% str()
indmap %>% select(-ends_with("description")) %>% mutate_if(is.character, as.factor) %>% summary()

```


About
====

Row 1
-----------------------------------------------------------------------

### About

Here is some content.
